export const ADD_PHONE_NUMBER_PAGE = "ADD_PHONE_NUMBER_PAGE";
export const VERIFY_PHONE_NUMBER_PAGE = "VERIFY_PHONE_NUMBER_PAGE";
export const ADD_PHONE_SUCCESS_PAGE = "ADD_PHONE_SUCCESS_PAGE";
export const PHONE_DISCOVERABILITY_CONSENT_PAGE =
  "PHONE_DISCOVERABILITY_CONSENT_PAGE";
