export default {
  consentToolModalTitle: "Heading.CookieSettings",
  saveBtn: "Action.SavePreferences",
  cancelBtn: "Action.Cancel",
  infoCollectionHeader: "Heading.InformationCollection",
  infoCollectionContent: "Description.InformationCollection",
  infoCollectionHeader2: "Heading.InformationCollection2",
  infoCollectionContent2: "Description.InformationCollection2",
  infoPartnerCollectionHeader: "Heading.InformationPartnerCollection",
  infoPartnerCollectionContent: "Description.InformationPartnerCollection",
  RBXViralAcquisition: {
    cookieName: "RBXViralAcquisition",
    description: "Description.RBXViralAcquisition",
  },
  RBXSource: {
    cookieName: "RBXSource",
    description: "Description.RBXSource",
  },
  googleAnalytics: "Heading.GoogleAnalytics",
  ownedBy: "Label.OwnedBy",
  googleInc: "Google Inc.",
  website: "Label.Website",
  googleAnalyticsPurposeHeader: "Heading.GoogleAnalyticsPurpose",
  googleAnalyticsPurposeDescription: "Description.GoogleAnalyticsPurpose",
  companyCollectionHeader: "Heading.CompanyCollection",
  GACompanyCollectionList: [
    { label: "Label.DataCollected", content: "Description.DataCollected" },
    { label: "Label.DataSharing", content: "Description.DataSharing" },
    { label: "Label.DataRetention", content: "Description.DataRetention" },
    { label: "Label.DataUse", content: "Description.DataUse" },
    { label: "Label.DataStorage", content: "Description.Undisclosed" },
  ],
  requestData: "Action.RequestData",
  essentialCookie: "Heading.EssentialCookies",
  analyticsCookie: "Heading.AnalyticsCookies",
  GAReadMore: "Description.GAReadMore",
  GAReadMoreUrl: "{googleAnalyticsLink}",
};
