const CLOSE_PHONE_NUMBER_MODAL = "CLOSE_PHONE_NUMBER_MODAL";
const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
const SET_PHONE_NUMBER_SEND_ERROR = "SET_PHONE_NUMBER_SEND_ERROR";
const SET_PHONE_NUMBER = "SET_PHONE_NUMBER";
const SET_COUNTRY = "SET_COUNTRY";
const SET_PAGE = "SET_PAGE";
const SET_PHONE_VERIFICATION_STATUS = "SET_PHONE_VERIFICATION_STATUS";
const SET_PREFIX_OPTIONS_LIST = "SET_PREFIX_OPTIONS_LIST";
const SET_LOGGING_VALUES = "SET_LOGGING_VALUES";
const SET_DISCOVERABILITY_CONSENT_PREFILL =
  "SET_DISCOVERABILITY_CONSENT_PREFILL";
export {
  CLOSE_PHONE_NUMBER_MODAL,
  SET_ERROR_MESSAGE,
  SET_PHONE_NUMBER_SEND_ERROR,
  SET_PHONE_NUMBER,
  SET_COUNTRY,
  SET_PAGE,
  SET_PHONE_VERIFICATION_STATUS,
  SET_PREFIX_OPTIONS_LIST,
  SET_LOGGING_VALUES,
  SET_DISCOVERABILITY_CONSENT_PREFILL,
};
